[pytest]
DJANGO_SETTINGS_MODULE = rds_agent.django_project.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = -v --tb=short
markers =
    django_db: marks tests as requiring django database